apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    app: frontend
